'use client'

import { useState } from 'react'
import type { ReactNode } from 'react'
import {
  Bell, Box, ChevronDown, ChevronRight, CircleHelp, Clock3, Download, ExternalLink,
  Eye, FileText, Home, ImagePlus, LayoutGrid, LogOut, Menu, MoreHorizontal, Package,
  Palette, Plus, Search, Settings, ShoppingBag, ShoppingCart, Smartphone, Store,
  Truck, Users, Wallet, X, Check, ArrowUpRight, MapPin, MessageCircle, CreditCard,
  Upload, Sparkles, SlidersHorizontal, CircleAlert, Loader2, WifiOff
} from 'lucide-react'

const products = [
  { name: 'Ensemble pagne Ankara', price: '35 000 FCFA', category: 'Mode', image: 'https://images.unsplash.com/photo-1596755389378-c31d21fd1273?auto=format&fit=crop&w=500&q=80', stock: true, sold: 12 },
  { name: 'Sac à main cuir camel', price: '18 500 FCFA', category: 'Accessoires', image: 'https://images.unsplash.com/photo-1584917865442-de89df76afd3?auto=format&fit=crop&w=500&q=80', stock: true, sold: 8 },
  { name: 'Robe fleurie été', price: '22 000 FCFA', category: 'Mode', image: 'https://images.unsplash.com/photo-1612336307429-8a898d10e223?auto=format&fit=crop&w=500&q=80', stock: false, sold: 5 },
  { name: 'Sandales artisanales', price: '12 000 FCFA', category: 'Chaussures', image: 'https://images.unsplash.com/photo-1560343090-f0409e92791a?auto=format&fit=crop&w=500&q=80', stock: true, sold: 17 },
]

const orders = [
  { id: '#MVC-1089', customer: 'Aminata K.', items: '2 articles', amount: '53 500 FCFA', time: 'Il y a 12 min', status: 'Nouveau', initials: 'AK', tone: 'blue' },
  { id: '#MVC-1088', customer: 'Yannick B.', items: '1 article', amount: '35 000 FCFA', time: 'Il y a 1 h', status: 'Confirmée', initials: 'YB', tone: 'orange' },
  { id: '#MVC-1087', customer: 'Djeneba S.', items: '3 articles', amount: '72 000 FCFA', time: 'Hier, 16:42', status: 'En livraison', initials: 'DS', tone: 'purple' },
  { id: '#MVC-1086', customer: 'Koffi A.', items: '1 article', amount: '18 500 FCFA', time: 'Hier, 14:20', status: 'Livrée', initials: 'KA', tone: 'green' },
]

const navItems = [
  { label: 'Vue d’ensemble', icon: Home, key: 'dashboard' },
  { label: 'Mes produits', icon: Package, key: 'products', count: '12' },
  { label: 'Commandes', icon: ShoppingCart, key: 'orders', count: '4' },
  { label: 'Ma vitrine', icon: Store, key: 'storefront' },
]

function Logo() {
  return <div className="brand"><span className="brand-mark"><Store size={19} strokeWidth={2.7} /></span><span>Ma Vitrine <b>CI</b></span></div>
}

function StatusBadge({ status, tone }: { status: string; tone?: string }) {
  return <span className={`status status-${tone || status.toLowerCase().replaceAll(' ', '-')}`}><span className="status-dot" />{status}</span>
}

function Sidebar({ active, setActive, onOnboarding }: { active: string; setActive: (key: string) => void; onOnboarding: () => void }) {
  return <aside className="sidebar">
    <div className="sidebar-top"><Logo /><button className="icon-button mobile-menu" aria-label="Fermer le menu"><X size={18}/></button></div>
    <div className="shop-switcher"><div className="shop-avatar">AD</div><div><strong>Awa Design</strong><small>mavitrine.ci/awadesign</small></div><ChevronDown size={16} /></div>
    <nav className="nav-list" aria-label="Navigation principale">
      <div className="nav-label">GESTION</div>
      {navItems.map(item => { const Icon = item.icon; return <button key={item.key} onClick={() => setActive(item.key)} className={`nav-item ${active === item.key ? 'active' : ''}`}><Icon size={18}/><span>{item.label}</span>{item.count && <em>{item.count}</em>}</button> })}
      <div className="nav-label nav-label-spaced">CONFIGURATION</div>
      <button onClick={() => setActive('customizer')} className={`nav-item ${active === 'customizer' ? 'active' : ''}`}><Palette size={18}/><span>Personnaliser</span></button>
      <button onClick={() => setActive('subscription')} className={`nav-item ${active === 'subscription' ? 'active' : ''}`}><Wallet size={18}/><span>Abonnement</span><span className="pro-pill">PRO</span></button>
    </nav>
    <div className="sidebar-bottom"><div className="help-card"><div className="help-icon"><CircleHelp size={18}/></div><div><strong>Besoin d’aide ?</strong><small>Notre équipe est là</small></div><ChevronRight size={15}/></div><button className="nav-item"><Settings size={18}/><span>Paramètres</span></button><button className="nav-item logout"><LogOut size={18}/><span>Se déconnecter</span></button><div className="profile"><div className="profile-avatar">AD</div><div><strong>Awa Diarra</strong><small>Vendeuse</small></div><MoreHorizontal size={17}/></div></div>
  </aside>
}

function BottomNav({ active, setActive }: { active: string; setActive: (key: string) => void }) {
  return <nav className="bottom-nav">{[...navItems.slice(0, 4), { label: 'Plus', icon: MoreHorizontal, key: 'more' }].map(item => { const Icon = item.icon; return <button key={item.key} onClick={() => setActive(item.key)} className={active === item.key ? 'active' : ''}><Icon size={19}/><span>{item.label === 'Vue d’ensemble' ? 'Accueil' : item.label === 'Mes produits' ? 'Produits' : item.label === 'Commandes' ? 'Commandes' : item.label === 'Ma vitrine' ? 'Vitrine' : 'Plus'}</span></button> })}</nav>
}

function Header({ title, subtitle, onMenu }: { title: string; subtitle: string; onMenu: () => void }) {
  return <header className="topbar"><button className="icon-button mobile-only" onClick={onMenu} aria-label="Ouvrir le menu"><Menu size={21}/></button><div><h1>{title}</h1><p>{subtitle}</p></div><div className="top-actions"><button className="view-store"><Eye size={16}/> Voir ma vitrine <ExternalLink size={13}/></button><button className="notification" aria-label="Notifications"><Bell size={19}/><span /></button><div className="top-avatar">AD</div></div></header>
}

function StatCard({ icon: Icon, label, value, change, tone, detail }: any) {
  return <div className="stat-card"><div className={`stat-icon ${tone}`}><Icon size={19}/></div><div className="stat-copy"><p>{label}</p><strong>{value}</strong><small className={change.startsWith('+') ? 'positive' : ''}><ArrowUpRight size={12}/>{change} <span>{detail}</span></small></div><MoreHorizontal size={17} className="stat-more" /></div>
}

function Dashboard({ setActive, onOnboarding }: { setActive: (key: string) => void; onOnboarding: () => void }) {
  return <><Header title="Bonjour Awa," subtitle="Voici ce qui se passe dans votre boutique aujourd’hui." onMenu={() => {}}/><main className="content">
    <div className="offline-banner"><WifiOff size={16}/><span>Vous êtes hors connexion. Vos données seront synchronisées dès le retour du réseau.</span><button>×</button></div>
    <section className="welcome-card"><div><span className="eyebrow">MARDI 22 SEPTEMBRE 2026</span><h2>Votre boutique est en pleine forme <span>!</span></h2><p>Continuez sur votre lancée, vous avez reçu <b>4 nouvelles commandes</b> aujourd’hui.</p><button className="primary-button" onClick={() => setActive('products')}><Plus size={17}/> Ajouter un produit</button></div><div className="welcome-art"><div className="sun-shape"/><div className="art-store"><Store size={46}/><div className="art-window"/></div><div className="art-leaf">✦</div></div></section>
    <div className="stats-grid"><StatCard icon={ShoppingCart} label="Commandes aujourd’hui" value="12" change="+18,2%" detail="vs. hier" tone="orange"/><StatCard icon={Eye} label="Visites de la vitrine" value="248" change="+24,5%" detail="vs. hier" tone="green"/><StatCard icon={Wallet} label="Chiffre d’affaires" value="286 500" change="+12,8%" detail="vs. hier" tone="gold"/></div>
    <div className="dashboard-grid"><section className="panel orders-panel"><div className="panel-heading"><div><h3>Commandes récentes</h3><p>Les dernières commandes de votre boutique</p></div><button className="text-button" onClick={() => setActive('orders')}>Voir toutes <ChevronRight size={15}/></button></div><div className="orders-list">{orders.map(order => <div className="order-row" key={order.id}><div className={`customer-avatar tone-${order.tone}`}>{order.initials}</div><div className="order-main"><strong>{order.customer}</strong><small>{order.id} · {order.items}</small></div><div className="order-time">{order.time}</div><div className="order-amount"><strong>{order.amount}</strong><StatusBadge status={order.status} tone={order.tone}/></div><ChevronRight size={16} className="row-chevron"/></div>)}</div></section><section className="panel performance-panel"><div className="panel-heading"><div><h3>Performance</h3><p>Ventes des 7 derniers jours</p></div><button className="period-button">Cette semaine <ChevronDown size={14}/></button></div><div className="chart-wrap"><div className="chart-value"><strong>286 500 FCFA</strong><span>+12,8%</span></div><div className="chart"><div className="chart-grid"><i/><i/><i/><i/></div><svg viewBox="0 0 500 170" preserveAspectRatio="none" aria-label="Graphique des ventes"><defs><linearGradient id="area" x1="0" x2="0" y1="0" y2="1"><stop offset="0" stopColor="#ff6b35" stopOpacity=".22"/><stop offset="1" stopColor="#ff6b35" stopOpacity="0"/></linearGradient></defs><path d="M0,138 C30,125 48,135 74,119 S113,100 140,111 S171,87 198,94 S235,106 262,78 S291,91 318,65 S350,86 374,58 S408,67 432,43 S471,52 500,23 L500,170 L0,170Z" fill="url(#area)"/><path d="M0,138 C30,125 48,135 74,119 S113,100 140,111 S171,87 198,94 S235,106 262,78 S291,91 318,65 S350,86 374,58 S408,67 432,43 S471,52 500,23" fill="none" stroke="#ff6b35" strokeWidth="3" strokeLinecap="round"/><circle cx="500" cy="23" r="5" fill="#fff" stroke="#ff6b35" strokeWidth="3"/></svg></div><div className="chart-labels"><span>Lun</span><span>Mar</span><span>Mer</span><span>Jeu</span><span>Ven</span><span>Sam</span><span>Dim</span></div></div></section></div>
    <section className="panel products-panel"><div className="panel-heading"><div><h3>Vos produits</h3><p>Les produits les plus consultés</p></div><button className="text-button" onClick={() => setActive('products')}>Gérer les produits <ChevronRight size={15}/></button></div><div className="mini-products">{products.slice(0, 4).map(product => <div className="mini-product" key={product.name}><img src={product.image} alt=""/><div><strong>{product.name}</strong><small>{product.sold} ventes</small></div><b>{product.price}</b></div>)}</div></section>
  </main></>
}

function ProductsView({ onAdd }: { onAdd: () => void }) { return <><Header title="Mes produits" subtitle="Gérez votre catalogue et gardez vos produits à jour." onMenu={() => {}}/><main className="content"><div className="page-actions"><div className="search-field"><Search size={17}/><input placeholder="Rechercher un produit..." /></div><button className="filter-button"><SlidersHorizontal size={16}/> Filtrer</button><button className="primary-button" onClick={onAdd}><Plus size={17}/> Ajouter un produit</button></div><div className="products-toolbar"><span><b>12 produits</b> dans votre catalogue</span><button>Les plus récents <ChevronDown size={14}/></button></div><div className="product-grid">{products.map(product => <article className="product-card" key={product.name}><div className="product-image"><img src={product.image} alt={product.name}/><button className="product-more" aria-label="Plus d'options"><MoreHorizontal size={17}/></button><span className={`stock-pill ${product.stock ? '' : 'out'}`}><span/> {product.stock ? 'En stock' : 'Épuisé'}</span></div><div className="product-info"><span>{product.category}</span><h3>{product.name}</h3><div><strong>{product.price}</strong><label className="switch"><input type="checkbox" defaultChecked={product.stock}/><i/></label></div></div></article>)}</div></main></> }

function OrdersView() { return <><Header title="Commandes" subtitle="Suivez et gérez les commandes de vos clients." onMenu={() => {}}/><main className="content"><div className="page-actions"><div className="search-field"><Search size={17}/><input placeholder="Rechercher une commande..." /></div><button className="filter-button"><SlidersHorizontal size={16}/> Tous les statuts <ChevronDown size={14}/></button><button className="outline-button"><Download size={16}/> Exporter</button></div><div className="order-tabs"><button className="active">Toutes <b>12</b></button><button>Nouvelles <b>4</b></button><button>En cours <b>5</b></button><button>Terminées <b>3</b></button></div><section className="panel orders-table-panel"><div className="table-head"><span>CLIENT</span><span>COMMANDE</span><span>MONTANT</span><span>STATUT</span><span>DATE</span><span/></div>{orders.map(order => <div className="table-row" key={order.id}><div className="customer-cell"><div className={`customer-avatar tone-${order.tone}`}>{order.initials}</div><strong>{order.customer}</strong></div><span>{order.id}<small>{order.items}</small></span><strong>{order.amount}</strong><StatusBadge status={order.status} tone={order.tone}/><span className="muted">22 sept. 2026</span><button className="icon-button"><MoreHorizontal size={18}/></button></div>)}</section></main></> }

function StorefrontView({ setActive }: { setActive: (key: string) => void }) { return <><Header title="Ma vitrine" subtitle="Voici comment vos clients voient votre boutique." onMenu={() => {}}/><main className="content"><div className="storefront-layout"><section className="customizer-panel"><div className="panel-heading"><div><h3>Personnaliser ma vitrine</h3><p>Donnez à votre boutique une identité qui vous ressemble.</p></div><button className="icon-button"><Settings size={18}/></button></div><div className="custom-field"><label>Nom de la boutique</label><input defaultValue="Awa Design" /></div><div className="custom-field"><label>Couleur du thème</label><div className="color-options"><button className="color-choice selected" style={{background:'#FF6B35'}}/><button className="color-choice" style={{background:'#2D9B4E'}}/><button className="color-choice" style={{background:'#6537c5'}}/></div></div><div className="custom-field"><label>Logo de la boutique</label><div className="logo-upload"><div className="upload-icon"><Upload size={17}/></div><div><strong>Glissez votre logo ici</strong><small>PNG ou JPG, 2 Mo max.</small></div><button>Parcourir</button></div></div><div className="custom-field"><label><MessageCircle size={15}/> Numéro WhatsApp</label><input defaultValue="+225 07 08 09 10 11" /></div><div className="custom-field"><label><MapPin size={15}/> Ville et quartier</label><input defaultValue="Abidjan, Cocody" /></div><button className="primary-button full-button"><Check size={17}/> Enregistrer les changements</button></section><section className="phone-preview"><div className="preview-heading"><span>Aperçu en direct</span><button onClick={() => setActive('public')}>Ouvrir <ExternalLink size={14}/></button></div><div className="phone-frame"><div className="phone-status"><span>9:41</span><span>● ◒ ▰</span></div><div className="phone-cover"><div className="cover-pattern"/><div className="preview-logo">AD</div></div><div className="preview-store-info"><h2>Awa Design</h2><p><MapPin size={12}/> Abidjan, Cocody</p><div className="preview-link"><span>mavitrine.ci/awadesign</span><ShareIcon/></div></div><div className="preview-chips"><span>Tout</span><span>Mode</span><span>Accessoires</span></div><div className="preview-grid">{products.slice(0,4).map(p => <div key={p.name}><img src={p.image} alt=""/><b>{p.name}</b><strong>{p.price}</strong></div>)}</div><button className="whatsapp-float"><MessageCircle size={16}/> WhatsApp</button></div></section></div></main></> }
function ShareIcon(){ return <ArrowUpRight size={13}/> }

function SubscriptionView() { return <><Header title="Mon abonnement" subtitle="Profitez de tous les outils pour développer votre activité." onMenu={() => {}}/><main className="content"><div className="trial-banner"><div className="trial-icon"><Sparkles size={20}/></div><div><strong>Votre essai gratuit se termine dans 12 jours</strong><p>Passez à un abonnement pour garder votre vitrine active et continuer à vendre.</p></div><button className="white-button">Voir les offres <ChevronRight size={15}/></button></div><div className="pricing-grid"><div className="pricing-card"><span>Mensuel</span><strong>2 500 <small>FCFA / mois</small></strong><p>Pour commencer simplement</p><button className="outline-button">Choisir ce plan</button></div><div className="pricing-card featured"><div className="popular">Le plus populaire</div><span>Trimestriel</span><strong>6 000 <small>FCFA / trimestre</small></strong><p>Économisez 20% sur 3 mois</p><button className="primary-button">Choisir ce plan</button></div><div className="pricing-card"><span>Annuel</span><strong>20 000 <small>FCFA / an</small></strong><p>La meilleure offre pour durer</p><button className="outline-button">Choisir ce plan</button></div></div><section className="panel billing-panel"><div className="panel-heading"><div><h3>Historique de facturation</h3><p>Retrouvez vos paiements précédents.</p></div><button className="text-button">Télécharger tout <Download size={15}/></button></div><div className="billing-row"><span><FileText size={17}/> Essai gratuit <small>22 sept. 2026</small></span><b>0 FCFA</b><span className="paid">Actif</span><Download size={16}/></div></section></main></> }

function ProductModal({ close }: { close: () => void }) { return <div className="modal-backdrop" onClick={close}><div className="modal" onClick={e => e.stopPropagation()}><div className="modal-header"><div><h2>Ajouter un produit</h2><p>Présentez votre produit à vos clients.</p></div><button className="icon-button" onClick={close}><X size={19}/></button></div><div className="upload-zone"><ImagePlus size={26}/><strong>Ajoutez les photos de votre produit</strong><small>Glissez-déposez jusqu’à 4 images, ou <u>parcourez vos fichiers</u></small></div><div className="form-grid"><label>Nom du produit<input placeholder="Ex. Robe fleurie été" /></label><label>Prix (FCFA)<input placeholder="Ex. 25 000" /></label></div><label>Description<textarea placeholder="Décrivez votre produit en quelques mots..." rows={4}/></label><div className="modal-footer"><button className="outline-button" onClick={close}>Annuler</button><button className="primary-button" onClick={close}><Check size={16}/> Enregistrer le produit</button></div></div></div> }

function Onboarding({ close }: { close: () => void }) { const [step, setStep] = useState(1); return <div className="modal-backdrop onboarding-backdrop"><div className="onboarding-card"><button className="close-onboarding" onClick={close}><X size={18}/></button><div className="onboarding-brand"><Logo/></div><div className="progress"><i className={step >= 1 ? 'done' : ''}/><i className={step >= 2 ? 'done' : ''}/><i className={step >= 3 ? 'done' : ''}/></div>{step === 1 && <div className="onboarding-content"><div className="onboarding-illustration"><Store size={48}/></div><span className="eyebrow">BIENVENUE SUR MA VITRINE CI</span><h2>Vendez plus, simplement.</h2><p>Créez votre vitrine en ligne et recevez vos commandes directement sur WhatsApp.</p><button className="primary-button full-button" onClick={() => setStep(2)}>Créer ma boutique <ChevronRight size={17}/></button><small>Déjà un compte ? <u>Se connecter</u></small></div>}{step === 2 && <div className="onboarding-content"><span className="eyebrow">ÉTAPE 2 SUR 3</span><h2>Votre numéro de téléphone</h2><p>Nous vous enverrons un code de vérification.</p><label className="onboarding-label">Numéro WhatsApp<input placeholder="+225 07 00 00 00 00" /></label><button className="primary-button full-button" onClick={() => setStep(3)}>Continuer <ChevronRight size={17}/></button></div>}{step === 3 && <div className="onboarding-content"><span className="eyebrow">ÉTAPE 3 SUR 3</span><h2>Parlez-nous de votre boutique</h2><p>Choisissez un nom qui vous ressemble.</p><label className="onboarding-label">Nom de la boutique<input placeholder="Ex. Awa Design" /></label><div className="url-preview"><span>mavitrine.ci/</span><b>awa-design</b></div><div className="category-grid"><button><span>✦</span>Mode</button><button><span>◌</span>Beauté</button><button><span>⌁</span>Alimentation</button><button><span>+</span>Autre</button></div><button className="primary-button full-button" onClick={close}>Lancer ma boutique <Sparkles size={16}/></button></div>}<div className="onboarding-footer">Sécurisé et pensé pour les vendeurs ivoiriens <span>·</span> <b>CI</b></div></div></div> }

export default function Page() { const [active, setActive] = useState('dashboard'); const [modal, setModal] = useState<'product' | 'onboarding' | null>(null); const [mobileMenu, setMobileMenu] = useState(false); const view = active === 'dashboard' ? <Dashboard setActive={setActive} onOnboarding={() => setModal('onboarding')}/> : active === 'products' ? <ProductsView onAdd={() => setModal('product')}/> : active === 'orders' ? <OrdersView/> : active === 'storefront' || active === 'public' ? <StorefrontView setActive={setActive}/> : active === 'customizer' ? <StorefrontView setActive={setActive}/> : <SubscriptionView/>; return <div className="app-shell"><div className={`sidebar-wrap ${mobileMenu ? 'open' : ''}`}><Sidebar active={active} setActive={(key) => {setActive(key); setMobileMenu(false)}} onOnboarding={() => setModal('onboarding')}/></div>{mobileMenu && <div className="mobile-overlay" onClick={() => setMobileMenu(false)}/>}<div className="main-area">{ReactClone(view, setMobileMenu)}</div><BottomNav active={active} setActive={setActive}/>{modal === 'product' && <ProductModal close={() => setModal(null)}/>} {modal === 'onboarding' && <Onboarding close={() => setModal(null)}/>}</div> }
function ReactClone(view: ReactNode, setMobileMenu: (value: boolean) => void) { return <div className="view-wrap">{view}</div> }
